# Generated by Django 3.2.9 on 2021-12-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrofac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='matricula',
            field=models.CharField(max_length=9),
        ),
    ]
